apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: devops-task
servers: 1
agents: 2
image: rancher/k3s:v1.36.2-k3s1
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: 120s
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
