{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-{{ $name }}
  labels:
    app: {{ $name }}
    {{- include "bookinfo.labels" $ | nindent 4 }}
{{- end }}
