apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-backups
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.backup.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backup.storage }}
